[content]
path = "content"

[public]
path = "public"

[build]
path = "docs"

[pages]
path = "pages"

[services]
    [services.alibot]
    name = "AliBot"
    status = "ok" # Could also de "degraded" or "down"
    #ongoingIssue = 1

    [services.mishisbot]
    name = "MishisBot"
    status = "ok"
    #ongoingIssue = 2

    [services.simpledeploy]
    name = "Simple Deploy"
    status = "ok"
    #ongoingIssue = 3

    [services.voter]
    name = "Voter"
    status = "ok"

    [services.skilltest]
    name = "SkillTest"
    status = "down"
    ongoingIssue = 4

    [services.whalechat]
    name = "Whale Chat"
    status = "down"
    ongoingIssue = 4

    [services.goodbye]
    name = "Goodbye"
    status = "down"
    ongoingIssue = 4
