[content]
path = "content"

[public]
path = "public"

[build]
path = "build"

[pages]
path = "pages"

[services]
    [services.dataapi]
    name = "Data API"
    status = "ok" # Could also de "degraded" or "down"
    #ongoingIssue = 1

    [services.premiumapi]
    name = "Premium API"
    status = "degraded"
    ongoingIssue = 2

    [services.enterpriseapi]
    name = "Enterprise API"
    status = "down"
    ongoingIssue = 3
